/*
 * Automatically generated by script/glsl2header.py
 */
/*
 * Copyright (C) 2023, unclearness
 * All rights reserved.
 */

#pragma once

#include <string>

namespace ugu {

static inline std::string geom_dummy_code =
    "#version 330 core\n"
    "\n"
    "void main() {}\n";
}
